export const regionsByMO = {
  Рыбинский: 'rybinskij_rajon',
  'Саянский район': 'sajanskij_rajon',
  'Северо-Енисейский район': 'severo-enisejskij_rajon',
  'Мотыгинский район': 'motyginskij_rajon',
  'Богучанский район': 'boguchanskij_rajon',
  'г. Лесосибирск': 'lesosibirsk',
  'Кежемский район': 'kazachinskij_rajon',
  'Таймырский (Долгано-Ненецкий)': 'tajmyrskaja_dolgano-neneckaja_tik_1',
  Туруханский: 'turukhanskij_rajon',
  Эвенкийский: 'ilimpijskaja_tik',
  'г. Норильск': 'norilsk',
  'г. Красноярск': 'central_nyj_rajon_krasnojarsk',
  'Березовский район': 'berezovskij_rajon',
  'г. Сосновоборск': 'sosnovoborsk',
  'Минусинский район': 'minusinskij_rajon',
  'Курагинский район': 'kuraginskij_rajon',
  'Шарыповский район': 'sharypovskij_rajon',
  'г. Дивногорск': 'divnogorsk',
  'ЗАТО г. Железногорск': 'zheleznogorsk',
  'Емельяновский район': 'emeljanovskij_rajon',
} as any;
